### DISCUSSION TITLE
MAM | Distinguish between VIP and Freeleech

### DISCUSSION THREAD

**Discussion by hasumedic** [autobrr/autobrr#1666] [Ideas]
This is a particular problem with MAM but it might be present in other trackers. Because VIP torrents are also Freeleech, autobrr parses them both the same way to detect whether a torrent is Freeleech.

That's OK, but there isn't currently a way to filter out VIP torrents (keeping only those that are site-wide freeleech) and viceversa.

A potential solution that was [described in Discord](https://discord.com/channels/881212911849209957/938041606232211488/1074955547801030706) by @s0up4200 might be worth implementing as a feature.

**Comment by IHateIssues** [comment]
Second this. As a new user who wants to build ratio quickly with autobrr I can’t do so without hassle of removing vip only torrents from qbittorrent because of this.

**Comment by buroa** [comment]
+1

**Comment by zivkovic** [comment]
Same here, was looking what was wrong, untill I found this issue.

**Comment by kaiserbh** [comment]
> Second this. As a new user who wants to build ratio quickly with autobrr I can’t do so without hassle of removing vip only torrents from qbittorrent because of this.

There is a simple workaround for this while waiting.

Essentially you have to create another filter in autobrr name it whatever you want, but just make sure to set the filter to freeleech only. Then after that in action just set it to test, save the filter and give it high priority add MaM indexer.

Should end up with something below.
![image](https://github.com/autobrr/autobrr/assets/41852205/e5956138-7347-44e7-a3fd-64b0577039b5)

Essentially the filter will be catch all type, that blocks the vip and let through non vip, it's pretty good for like building ratio for new member anyway, at the very least until they become vip member 💀.

**Reply by Couchtater** [reply]
Hi!

So I understand how to use the freeleech toggle to block VIP torrents. For the filter to actually download freeleech torrents do i still use the toggle? Or do I use the  %% freeleech and set to 100% ?

**Comment by zze0s** [comment]
There was a discussion about this in Discord this weekend. TLDR of that was freeleech is not announced but added afterwards. 

VIP is announced and parsed as freeleech atm in autobrr which is not ideal because there is no "ignore freeleech". We're planning on making the change suggested in OPs link to Discord which is to change the parsing to `releaseTags` instead of `freeleech` so it can be filtered with `Match/Except Release Tags`. We'll have to make some custom migration of filters for that however.

Here's a full definition file that has this change which can be used via [customDefinitions](https://autobrr.com/configuration/indexers#custom-indexer-definitions). This one overrides the built in indexer definition.

```yaml
---
#id: tracker01
name: MyAnonamouse
identifier: myanonamouse
description: MyAnonaMouse (MAM) is a large ebook and audiobook tracker.
language: en-us
urls:
  - https://www.myanonamouse.net/
privacy: private
protocol: torrent
supports:
  - irc
  - rss
# source: custom
settings:
  - name: cookie
    type: secret
    required: true
    label: Cookie (mam_id)
    help: "Check how to get cookies in your browser and find the mam_id cookie. Changes monthly. Format mam_id=$ID;"

irc:
  network: MyAnonamouse
  server: irc.myanonamouse.net
  port: 6697
  tls: true
  channels:
    - "#announce"
  announcers:
    - MouseBot
  settings:
    - name: nick
      type: text
      required: true
      label: Nick
      help: Bot nick. Eg. user_bot

    - name: auth.account
      type: text
      required: true
      label: NickServ Account
      help: NickServ account. Make sure to group your user and bot. Use main nick here.

    - name: auth.password
      type: secret
      required: true
      label: NickServ Password
      help: NickServ password

  parse:
    type: single
    lines:
      - tests:
        - line: 'New Torrent: Some famous book By: Author name Category: ( Ebooks - Science Fiction ) Size: ( 1.00 MiB ) Filetype: ( epub, mobi ) Language: ( English ) Link: ( https://www.myanonamouse.net/t/000000 )'
          expect:
            torrentName: Some famous book
            author: Author name
            category: Ebooks - Science Fiction
            torrentSize: 1.00 MiB
            tags: epub, mobi
            language: English
            baseUrl: https://www.myanonamouse.net/
            torrentId: "000000"
            releaseTags: ""
        - line: 'New Torrent: Some famous book By: Author name Category: ( Ebooks - Science Fiction ) Size: ( 2.11 MiB ) Filetype: ( epub, mobi ) Language: ( English ) Link: ( https://www.myanonamouse.net/t/000000 ) VIP'
          expect:
            torrentName: Some famous book
            author: Author name
            category: Ebooks - Science Fiction
            torrentSize: 2.11 MiB
            tags: epub, mobi
            language: English
            baseUrl: https://www.myanonamouse.net/
            torrentId: "000000"
            releaseTags: VIP
        pattern: 'New Torrent: (.*) By: (.*) Category: \( (.*) \) Size: \( (.*) \) Filetype: \( (.*) \) Language: \( (.*) \) Link: \( (https?\:\/\/[^\/]+\/).*?(\d+)\s*\)\s*(VIP)?'
        vars:
          - torrentName
          - author
          - category
          - torrentSize
          - tags
          - language
          - baseUrl
          - torrentId
          - releaseTags

    match:
      infourl: "/t/{{ .torrentId }}"
      torrenturl: "/tor/download.php?tid={{ .torrentId }}"
      torrentname: "{{ .torrentName }} by {{ .author }} [{{ .language }} / {{ .tags }}]"
```
