### DISCUSSION TITLE
Include whether or not an IRC server is enabled by a user as a label for Prometheus metrics

### DISCUSSION THREAD

**Discussion by onedr0p** [autobrr/autobrr#2035] [Ideas]
Hi 👋 

I am using Alertmanager to alert on unhealthy IRC servers using the promql query:

```promql
autobrr_irc_channel_enabled_total != autobrr_irc_channel_monitored_total
```

This works great with the exception that I cannot disable IRC servers in autobrr. When I disable an IRC server in autobrr my alert triggers for the IRC servers I have disabled. Ideally I would like to omit IRC servers that I am manually disabled via a query like:

```promql
autobrr_irc_channel_enabled_total{enabled="true"} != autobrr_irc_channel_monitored_total{enabled="true"}
```

I couldn't find any other way to accomplish this using the existing metrics and labels.

**Comment by onedr0p** [comment]
@Intuinewin as I saw you initially added Prometheus support for autobrr, would this be something you could take a look at?

**Reply by Intuinewin** [reply]
An alert like this doesn't work ? `autobrr_irc_channel_enabled_total - autobrr_irc_channel_monitored_total > 0`

I need to try on my instance it's weird. I currently only monitor irc_servers and not channels

**Reply by onedr0p** [reply]
I have it monitor the networks so that I can get an alert with the network name that is having trouble, e.g.

```yaml
- name: autobrr.rules
  rules:
    - alert: AutobrrNetworkUnmonitored
      expr: |
        autobrr_irc_channel_enabled_total != autobrr_irc_channel_monitored_total
      for: 5m
      annotations:
        summary: >-
          {{ $labels.network }} is not being monitored by Autobrr
      labels:
        severity: critical
```

Your query does not work, it still returns disabled IRC servers:

<img width="1488" alt="image" src="https://github.com/user-attachments/assets/a4bc8734-568b-4d4d-9490-604231b879a2" />

Thanks and sorry for the initial ping 😄
