### ISSUE TITLE
milkie - irc scraper needs updating

### ISSUE THREAD

**Issue by dyno54** [autobrr/autobrr#1471]
**Version**
1.39.1

**Describe the bug**
Scraper out of date

Example:
12:41:29DBG{music} :: RELEASE-GRP :: [flac] :: https://milkie.cc/browse/3YxHSdkD7AtX channel=#milkie-announce module=irc network=irc.p2p-network.net nick=the_cow
12:41:29DBG(flac1) for release: RELEASE-GRP rejections: (release type not matching. got: music want: [Album Anthology Bootleg Compilation Concert Recording Demo DJ Mix EP Interview Live album Mixtape Remix Sampler Single Soundtrack Unknown], quality not matching. got: [FLAC] want: [Lossless 24bit Lossless]) method=CheckFilter module=filter

**Comment by dyno54** [comment]
The scraper is pulling the wrong part for "release_types".  Also there is no "quality" field in irc, its already trying to match on.

```JSON
{
    "name": "flac1",
    "version": "1.0",
    "data": {
        "min_size": "50",
        "max_size": "150",
        "max_downloads_unit": "DAY",
        "years": "2023-2024",
        "artists": "*",
        "albums": "*",
        "match_release_types": [
            "Album",
            "Anthology",
            "Bootleg",
            "Compilation",
            "Concert Recording",
            "Demo",
            "DJ Mix",
            "EP",
            "Interview",
            "Live album",
            "Mixtape",
            "Remix",
            "Sampler",
            "Single",
            "Soundtrack",
            "Unknown"
        ],
        "formats": [
            "FLAC"
        ],
        "quality": [
            "Lossless",
            "24bit Lossless"
        ],
        "media": [
            "CD",
            "WEB",
            "DVD",
            "Vinyl",
            "Soundboard",
            "DAT",
            "Cassette",
            "Blu-Ray",
            "SACD"
        ]
    }
}
```

**Comment by zze0s** [comment]
`music` is their category, so use Match Categories for that.

Matching their tags like `flac` it does best effort to map it to some value. Their announce is generic and not strictly just music so there's caveats and limitations.

You can see here what it maps which part to https://github.com/autobrr/autobrr/blob/develop/internal/indexer/definitions/milkie.yaml#L57-L70

```yaml
  parse:
    type: single
    lines:
      - tests:
        - line: '{tv} :: The.Great.Xmas.Show.S00E00.1080p.WEB.H264-TEST :: [1080p, web] :: https://milkie.cc/browse/xxxxxxxxxxxx'
          expect:
            category: tv
            torrentName: The.Great.Xmas.Show.S00E00.1080p.WEB.H264-TEST
            releaseTags: 1080p, web
            baseUrl: https://milkie.cc/
            torrentId: xxxxxxxxxxxx
        pattern: '{(.*)}\s::\s(.*)\s::\s\[(.*)\]\s::\s(https?\:\/\/[^\/]+\/)browse\/(.*)'
        vars:
          - category
          - torrentName
          - releaseTags
          - baseUrl
          - torrentId
```
