### ISSUE TITLE
Greedy matching of PTP announce will break if additional vars are added following the existing announce format

### ISSUE THREAD

**Issue by doomtop** [autobrr/autobrr#1609]
https://github.com/autobrr/autobrr/blob/6b3a4c5c63427c52720c1af61c0076cbf7b85b93/internal/indexer/definitions/ptp.yaml#L112

Currently this works with the current announce structure.

Given an announce like:

> That Movie [1972] by Some Director | x264 / Blu-ray / MKV / 1080p | 204371 | 964303 | That.Movie.1972.1080p.BluRay.FLAC.x264-GROUP | comedy, drama, romance

Will result in:

```yaml
year: "1972"
releaseTags: x264 / Blu-ray / MKV / 1080p
freeleech: ""
torrentId: "964303"
torrentName: "That.Movie.1972.1080p.BluRay.FLAC.x264-GROUP"
tags: "comedy, drama, romance"
```

However, if the announce format were augmented to add an additional var, such as IMDB ID, resulting in an announce like:

> That Movie [1972] by Some Director | x264 / Blu-ray / MKV / 1080p | 204371 | 964303 | That.Movie.1972.1080p.BluRay.FLAC.x264-GROUP | comedy, drama, romance | tt12345678

You would instead get an incorrect result:

```yaml
year: "1972"
releaseTags: 204371
freeleech: ""
torrentId: "That.Movie.1972.1080p.BluRay.FLAC.x264-GROUP"
torrentName: "comedy, drama, romance"
tags: "tt12345678"
```

Assuming PTP maintained the existing announce structure of `var | var | var | var | var | var` they could continue adding additional vars in similar format (e.g. `var | var | var | var | var | var | var` and so on...) without breaking the existing pattern, if the pattern were to be adjusted to use lazy matching with ~~lookahead~~ optional check for additional `|` delimiter(s).

This would allow PTP to add additional parameters to their announce format, following the existing structure format, without requiring changes to the existing pattern. Currently, such a change to the announce format would require publishing new code and end users to update their client version in order to continue functioning correctly, regardless whether autobrr makes any use whatsoever of the new parameters.
