### ISSUE TITLE
OIDC options are documented incorrectly

### ISSUE THREAD

**Issue by pta2002** [autobrr/autobrr#1970]
**Version**
1.58.0

**Describe the bug**
For setting the OIDC options, the documentation (and auto-generated config) suggest setting the OIDC-related options in camelCase, but they need to be specified in snake_case to work.

**To Reproduce**

Use the [documented settings](https://autobrr.com/configuration/authentication#enable-oidc-in-autobrr):

```toml
oidcEnabled = true
oidcIssuer = "https://your-identity-provider"
oidcClientId = "your-client-id"
oidcClientSecret = "your-client-secret"
oidcRedirectUrl = "https://your-autobrr-instance/api/auth/oidc/callback"
oidcDisableBuiltInLogin = false
```

**Expected behavior**
OIDC is enabled and the option shows up in the login form.

**Additional context**
For the options to take effect, they need to be set in the following way:

```toml
oidc_enabled = true
oidc_issuer = "https://your-identity-provider"
oidc_client_id = "your-client-id"
oidc_client_secret = "your-client-secret"
oidc_redirect_url = "https://your-autobrr-instance/api/auth/oidc/callback"
disable_built_in_login = false
```
