### ISSUE TITLE
Read config from docker secrets ENV_VAR_FILE

### ISSUE THREAD

**Issue by zze0s** [autobrr/autobrr#2063]
Read env vars from docker secrets env file.

```yaml
services:
  db:
    image: mysql:latest
    volumes:
      db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      db_root_password
      db_password

secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt

volumes:
  db_data:
```

> The gist is to read (.$)__FILE envs, where $1 is the variable you usually look for, and the content of the _FILE env points to a file for where you read the content as the valie of $1.
> container is started with -e MY_TOKEN_FILE=/run/secret/randomfile
> if done in bash you could do something crude like export MY_TOKEN=$(cat $MY_TOKEN_FILE)
