### ISSUE TITLE
[FEATURE REQ] Proxy support

### ISSUE THREAD

**Issue by stxmqa** [autobrr/autobrr#728]
**Is your feature request related to a problem? Please describe.**
All my *arr apps make requests to various indexer sites via a proxy I have running in docker. Autobrr seems to be the only one directly connecting to indexer's sites to download torrents. This is problematic for indexers that require a cookie to be set specifically from a client IP moreover it also exposes my internet IP address.

**Describe the solution you'd like**
I want to be able to specify a socks proxy for autobrr 

**Describe alternatives you've considered**
Not sure I could find an alternative here besides having the whole box running the VPN would defeat the isolation docker provides. Moreover, allows me running different docker containers with different VPNs for their purposes.

**Additional context**

Unsure if setting a PROXY container variable would work. If that works I didn't find it documented.

All *arr apps support setting a proxy to contact third party services therefore autobrr supporting that would be helpful.

**Comment by giacomo-c** [comment]
you can do this by setting the environment variable http_proxy or https_proxy in either your compose file or as a command argument.

https://docs.docker.com/network/proxy/#run-containers-with-a-proxy-configuration

**Comment by Buenno** [comment]
I can't find any documentation on adding a proxy to the compose file, any help with this would be appreciated. As of last week, I can't use autobrr as my ISP decided to block all of my indexers. I can't route this through my VPN as I don't know how to communicate with other containers outside of the VPN (that aren't connected to the VPN).

**Comment by giacomo-c** [comment]
I am definitely no expert, but this is what worked for me:  https://hub.docker.com/r/binhex/arch-privoxyvpn
I just use the http proxy, but it does have socks so you could mess around with that to see if it will work.  Some quick searches I see adding the proxy container as the [net variable](https://www.reddit.com/r/selfhosted/comments/yoekzx/force_docker_container_to_use_socks5_proxy/) for the autobrr container may work (I have not tried this), or possibly just specifying the socks protocol with `http_proxy=socks5://user:pass@ip:port`, but you'd have to test that out as I don't see anyone confirming this does this trick.

For my simple http proxy this is what my compose looks like:

```
version: "3.7"

services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - no_proxy=localhost,127.0.0.0/8
      - http_proxy=http://privoxycontainer:port
    user: 1000:1000
    volumes:
      - ${BASE_DOCKER_DATA_PATH}/autobrr/config:/config
    ports:
      - 7474:7474
```

I already had the privoxyvpn container setup with a wireguard connection, so all I had to do for autobrr was checkout that docker documentation and add the environmental variables, then test from inside the container.

```
host@docker $  sudo docker exec -it autobrr /bin/sh
/app $  curl http://ipecho.net/plain; echo
```
